Datafile accessor
optimizely/php-sdk pull request #211
Opened 2020-08-25 16:52 UTC by ozayr-zaviar

## Summary
- toDatafile() method added in DatafileProjectConfig.php to fetch datafile.
- getDatafile() method added in OptimizelyConfig.php to fetch datafile.

## Test plan
- Repective testcases added as well

2020-08-25 17:13 UTC, aliabbasrizvi commented
@ozayr-zaviar can you take care of signing our CLA mentioned in the CONTRIBUTING document?

2020-08-27 10:13 UTC, oakbani requested changes
Please address.

2020-08-27 10:13 UTC, oakbani commented on src/Optimizely/Config/ProjectConfigInterface.php
> +     * Determines if given experiment is a feature test.
nit. Fix this docstring

2020-08-27 10:13 UTC, oakbani commented on src/Optimizely/OptimizelyConfig/OptimizelyConfigService.php
> +        $this->datafile = $$projectConfig->toDatafile();
nit $$

2020-08-27 10:13 UTC, oakbani commented on src/Optimizely/OptimizelyConfig/OptimizelyConfig.php
> +    public function __construct($revision, array $experimentsMap, array $featuresMap, $datafile = null)
do not provide a default null for datafile.

2020-08-27 10:13 UTC, oakbani commented on src/Optimizely/OptimizelyConfig/OptimizelyConfigService.php
> +        $this->datafile = $$projectConfig->toDatafile();
You haven't passed datafile to new OptimizelyConfig below

2020-08-27 10:13 UTC, oakbani commented on tests/ConfigTests/DatafileProjectConfigTest.php
> +namespace Optimizely\Tests;
Please fix this file. This should only show diff of the new unit test you have added.

2020-08-27 10:13 UTC, oakbani commented on tests/OptimizelyConfigTests/OptimizelyConfigServiceTest.php
> +        $actualDatafile = $this->optConfigService->getDatafile();
getDatafile() has been defined for OptimizelyConfig, not OptimizelyConfigService.

2020-08-27 18:38 UTC, oakbani commented
@msohailhussain  Testapp PR should be merged to get FSC passed https://github.com/optimizely/php-testapp/pull/65

2020-08-27 19:24 UTC, msohailhussain commented on src/Optimizely/Config/DatafileProjectConfig.php
> +    private $datafile;
shouldn't it be $_datafile?

2020-08-27 19:25 UTC, msohailhussain commented on src/Optimizely/OptimizelyConfig/OptimizelyConfig.php
> +    private $datafile;
same here.

2020-08-27 19:26 UTC, zashraf1985 commented on src/Optimizely/Config/DatafileProjectConfig.php
> +    private $datafile;
This should probably be `$_datafile` to be consistent with other private variable conventions. @oakbani ?

2020-08-27 19:28 UTC, msohailhussain commented on src/Optimizely/OptimizelyConfig/OptimizelyConfig.php
> +    public function __construct($revision, array $experimentsMap, array $featuresMap, $datafile)
won't it break existing functionality?

2020-08-27 19:28 UTC, msohailhussain commented on tests/OptimizelyConfigTests/OptimizelyEntitiesTest.php
> +            null
this shouldn't be changed.

2020-08-27 19:28 UTC, msohailhussain commented on tests/OptimizelyConfigTests/OptimizelyEntitiesTest.php
> +            "datafile": null
same here.

2020-08-27 22:06 UTC, aliabbasrizvi commented on src/Optimizely/Config/DatafileProjectConfig.php
> +    private $datafile;
I think the privacy convention has changed. I think @oakbani had showed me that previously. See: https://www.php-fig.org/psr/psr-12/#43-properties-and-constants

2020-08-27 22:06 UTC, aliabbasrizvi commented on src/Optimizely/OptimizelyConfig/OptimizelyConfig.php
> +    private $datafile;
https://www.php-fig.org/psr/psr-12/#43-properties-and-constants

2020-08-27 22:26 UTC, aliabbasrizvi commented on src/Optimizely/OptimizelyConfig/OptimizelyConfigService.php
> +     * @var string config datafile.
nit. `@var string String denoting datafile.`

2020-08-28 19:56 UTC, merged