feature: add semantic version types
optimizely/php-sdk pull request #213
Opened 2020-08-28 18:04 UTC by yasirfolio3

## Summary
- add greater than or equal and less than or equal for numbers
- add semantic version match types.

2020-08-31 08:15 UTC, oakbani reviewed
Some changes requested.

2020-08-31 08:15 UTC, oakbani commented on src/Optimizely/Utils/CustomAttributeConditionEvaluator.php
> +        if ($comparison !== null) {
nit. Will be more readable if you do:
`if ($comparison === null) {
    return null
}
return $comparison === 0
`
For all others too

2020-08-31 08:15 UTC, oakbani commented on tests/UtilsTests/CustomAttributeConditionEvaluatorTest.php
> +        $customAttrConditionEvaluator = new CustomAttributeConditionEvaluator(
nit. define the condition inside this method just like you have done below. testSemVerGTMatcherReturnsTrueWhenAttributeValueIsGreaterThanConditionValueBeta()

2020-08-31 08:15 UTC, oakbani commented on tests/UtilsTests/CustomAttributeConditionEvaluatorTest.php
> +        foreach ($invalidValues as $val) {
can you write the above tests in a for loop just like you have done here? 
seta  custom error message and send it to assert call as last argument.

2020-09-04 08:07 UTC, oakbani requested changes
Rather than creating SemVersionConditionEvaluator as a separate class and creating it's instance on every evaluation call. Make method inside SemVerionEvaluator static. And directly use them from different evaluator methods. Pass logger as a param to compare_version static method. And move string validation to compare_version method as well. 

compare_version should get (target_version, user_version, logger)

2020-09-04 08:07 UTC, oakbani commented on src/Optimizely/Utils/SemVersionConditionEvaluator.php
> +            $targetParts = explode($this->isPreRelease($targetPrefix) ? self::PRE_RELEASE_SEPARATOR : self::BUILD_SEPARATOR, $targetedVersion, 2);
`$this->isPreRelease($targetPrefix) ? self::PRE_RELEASE_SEPARATOR : self::BUILD_SEPARATOR` assign this to a variable before use. Readability.

2020-09-04 08:07 UTC, oakbani commented on src/Optimizely/Utils/SemVersionConditionEvaluator.php
> +        $versionParts = $this->splitSemanticVersion($this->condition);
nit. rename userVersionParts

2020-09-04 08:07 UTC, oakbani commented on src/Optimizely/Utils/SemVersionConditionEvaluator.php
> +            if (count($versionParts) <= $i) {
`count($versionParts)` assign this to a variable at top and resuse

2020-09-04 08:07 UTC, oakbani commented on src/Optimizely/Utils/SemVersionConditionEvaluator.php
> +                // even if they are equal at this point. if the target is a prerelease then it must be greater than the pre release.
nit. looks like there is something wrong with this comment.

2020-09-04 13:55 UTC, oakbani approved these changes
Looks good.

2020-09-04 13:55 UTC, oakbani commented on src/Optimizely/Utils/CustomAttributeConditionEvaluator.php
> +        if (!Validator::validateNonEmptyString($conditionValue) || !Validator::validateNonEmptyString($userValue)) {
just remove the check for conditionValue. We assume that we get string semantic version value from the datafile/backend. 
And in case of bad condition value, the error message being logged is misleading.

2020-09-04 13:55 UTC, oakbani commented on src/Optimizely/Utils/CustomAttributeConditionEvaluator.php
> +        if (!Validator::validateNonEmptyString($conditionValue) || !Validator::validateNonEmptyString($userValue)) {
nit. 
Modify doc string of this method to returns result of SemVersionConditionEvaluator::compareVersion for given target and user versions.

2020-09-04 17:23 UTC, oakbani reviewed
@yasirfolio3 Code Optimization

2020-09-04 17:23 UTC, oakbani commented on src/Optimizely/Utils/SemVersionConditionEvaluator.php
> +            $separator = self::isPreRelease($targetPrefix) ? self::PRE_RELEASE_SEPARATOR : self::BUILD_SEPARATOR;
`self::isPreRelease($targetPrefix)`
nit. do this once
if (self::isPreRelease)
    $separator = ...
elseif(self::isBuild)
 $separator = ...

2020-09-04 17:23 UTC, oakbani commented on src/Optimizely/Utils/SemVersionConditionEvaluator.php
> +        return 0;
assign self::isPreRelease($targetedVersion) and self::isPreRelease($userVersion) to variables at the top of this method. And reuse them at all places.

2020-09-08 20:35 UTC, aliabbasrizvi commented on src/Optimizely/Utils/SemVersionConditionEvaluator.php
> +        if (!$isPreReleaseTargetedVersion && $isPreReleaseUserVersion) {
nit. Can you leave a comment here about what is being checked?

2020-09-08 20:35 UTC, aliabbasrizvi commented on src/Optimizely/Utils/SemVersionConditionEvaluator.php
> +    private static function isBuild($version)
nit. `isBuildVersion`

2020-09-08 20:35 UTC, aliabbasrizvi commented on src/Optimizely/Utils/SemVersionConditionEvaluator.php
> +    private static function isPreRelease($version)
nit. `isPreReleaseVersion`

2020-09-14 16:24 UTC, aliabbasrizvi commented on src/Optimizely/Utils/SemVersionConditionEvaluator.php
> +     * @return null|int 0 if user's semver attribute is equal to the semver condition value,
nit. `user's attribute` or `user's version attribute`

2020-09-14 16:25 UTC, aliabbasrizvi approved these changes

2020-09-14 16:25 UTC, aliabbasrizvi commented on src/Optimizely/Utils/SemVersionConditionEvaluator.php
> +     * @return null|int 0 if user's semver attribute is equal to the semver condition value,
Please apply this feedback throughout the PR.

2020-09-15 04:37 UTC, msohailhussain approved these changes
lgtm

2020-09-15 04:58 UTC, merged