feat(Decide): Add Decide API
optimizely/php-sdk pull request #220
Opened 2020-11-24 13:53 UTC by oakbani

## Summary
Added new Apis to support the decide feature. Introduced a new `OptimizelyUserContext ` class through `createUserContext` class api. This creates an optimizely instance with memoized user context and exposes the following APIs
1. `setAttribute`
2. `decide`
3. `decideAll`
4. `decideForKeys`
5. `trackEvent`

## Test plan
1. Manually tested thoroughly.
2. Added unit tests to cover new functionality. **todo:** To add further tests. 
3. Tested with FSC manually.

2020-12-11 00:51 UTC, jaeopt requested changes
It looks great!
A couple of fixes necessary and more tests suggested.

2020-12-11 00:51 UTC, jaeopt commented on tests/OptimizelyUserContextTests.php
> +
Can we add a test: 
- no attributes given at init and added later with setAttribute

2020-12-11 00:51 UTC, jaeopt commented on tests/OptimizelyTest.php
> +                'featureEnabled'=> true,
```suggestion
                'enabled'=> true,
```

2020-12-11 00:51 UTC, jaeopt commented on tests/OptimizelyTest.php
> +        $this->assertEquals($expectedOptimizelyDecision->getFlagKey(), $optimizelyDecision->getFlagKey());
This line is redundant. "reasons" not compared. Is it intentional?

2020-12-11 00:51 UTC, jaeopt commented on tests/OptimizelyTest.php
> +            );
remove?

2020-12-11 00:51 UTC, jaeopt commented on tests/OptimizelyTest.php
> +
I do not see tests for
- INCLUDE_REASONS
- IGNORE_USER_PROFILE (skip read/write UPS both)

2020-12-11 00:51 UTC, jaeopt commented on tests/OptimizelyTest.php
> +
Also need the same set of tests for "default_decide_options".

And I'd like to see a test validating options in "default_decide_options" (EXCLUDE_VARIABLES) and decide parameter option (DISABLE_DECIDE_EVENTS) work together ok.

2020-12-11 13:39 UTC, oakbani commented on src/Optimizely/Optimizely.php
> +            $decideReasons
I think this is a clean approach. 
- Here decideReasons is passed by reference. If we choose not to pass here based on INCLUDE_REASONS flag, each internal method would create a default array inside method, push log into it and eventually lose it's scope. 
- The other thing that we can do is to pass decideOptions in each method with the decideReasons. And check for INCLUDE_REASONS flag inside decideOptions before pushing any log in decideReasons array. This would add an additonal array item check before each log.

2020-12-11 14:17 UTC, oakbani commented on src/Optimizely/Optimizely.php
> +    public function decide(OptimizelyUserContext $userContext, $key, array $decideOptions = [])
If I am correct, this won't be possible in PHP as it doesn't provide package level visibility. Making any of these methods protected / private, would make them unreachable from OptimizelyUserContext class.

2020-12-11 14:21 UTC, oakbani commented on src/Optimizely/OptimizelyUserContext.php
> +        $this->attributes[$key] = $value;
PHP is used in a single-threaded environment. Therefore, it's not needed.

2020-12-11 14:27 UTC, oakbani commented on tests/OptimizelyTest.php
> +        $this->assertEquals($expectedOptimizelyDecision->getFlagKey(), $optimizelyDecision->getFlagKey());
Yes, left out reasons comparison intentionally. As in all those tests, where INCLUDE_REASONS flag is included, we will have to create a verbose expected OptimizelyDecision object. Reasons are asserted separately.

2020-12-11 18:00 UTC, jaeopt requested changes
All changes look good!
One last missing test is IGNORE_USER_PROFILE option testing. Add a test validating both reading and updating skipped on the option.

2020-12-14 17:20 UTC, jaeopt approved these changes
LGTM

2021-01-20 07:15 UTC, oakbani commented
@msohailhussain  @jaeopt  ready to merge

2021-01-21 19:37 UTC, merged