refact: return decide reasons instead of appending to a reference parameter
optimizely/php-sdk pull request #221
Opened 2020-12-17 08:01 UTC by oakbani

## Summary
This PR refactors the way we collect logs for decideReasons. Previously, an array was being passed as reference to each method and each method appended it's log in the passed array. Now, each method returns it's logs along with it's response. 

## Test plan
- Modified Unit Tests.
- All existing checks should pass.

## Issues
- "THING-1234" or "Fixes #123"

2020-12-17 18:19 UTC, jaeopt requested changes
It looks good!
Can we add a few more tests validating reasons collecting for decision hierarchical paths. No need for validating all messages.

2020-12-17 18:19 UTC, jaeopt commented on tests/DecisionServiceTests/DecisionServiceTest.php
> +        $forcedVariationKey  = $optlyObject->getVariation($experimentKey, $userId, $userAttributes);
nit: remove space

2020-12-17 18:19 UTC, jaeopt commented on tests/DecisionServiceTests/DecisionServiceTest.php
> +        // $this->assertNull($forcedVariationKey);
Why these tests commented out? Intentional?

2020-12-21 14:00 UTC, oakbani commented on tests/DecisionServiceTests/DecisionServiceTest.php
> +        // $this->assertNull($forcedVariationKey);
Nice catch. Probably was trying to test something and forgot to revert it.

2021-01-07 19:39 UTC, jaeopt approved these changes
LGTM

2021-01-08 13:26 UTC, merged