clone function created and passed as argument in decide API
optimizely/php-sdk pull request #224
Opened 2021-01-12 11:09 UTC by ozayr-zaviar

Summary
-------
-  `clone()` added in user_context to clone user_context and passed in `decide`, `decide_for_keys`and `decide_all` as argument

Test plan
---------
- All existing test cases should pass

2021-01-13 07:36 UTC, oakbani requested changes
Looks good. Can you check why the build is only failing on PHP 5.6 and 5.6? Is clone a reserved keyword?

2021-01-13 07:36 UTC, oakbani commented on src/Optimizely/OptimizelyUserContext.php
> +    public function clone()
let's keep this protected for now

2021-01-13 07:36 UTC, oakbani commented on src/Optimizely/OptimizelyUserContext.php
> +        return $this->optimizelyClient->decide($this->clone(), $key, $options);
Can you add a unit test that verifies that the OptimizelyUserContext object received in decide response is not the same object on which the decide was called?

2021-01-14 07:57 UTC, oakbani approved these changes
Looks good. Just a minor comment.

2021-01-14 07:57 UTC, oakbani commented on tests/OptimizelyUserContextTests.php
> +        $this->assertNotEquals(
Why don't you directly compare the user context objects?

2021-01-14 19:37 UTC, jaeopt requested changes
Looks good. A test change suggested.

2021-01-14 19:37 UTC, jaeopt commented on tests/OptimizelyUserContextTests.php
> +        );
Can we also check if the returned userContext equal to the original user/attributes.

2021-01-14 19:41 UTC, jaeopt commented on src/Optimizely/OptimizelyUserContext.php
> +    protected function replicate()
rename to "copy" (or "clone")? Are they reserved?

2021-01-22 14:53 UTC, oakbani commented
@jaeopt  rebased to master and addressed comments.

2021-01-22 17:46 UTC, jaeopt approved these changes
LGTM

2021-01-22 17:47 UTC, merged