feat: Duplicate experiment key issue with multi feature flag
optimizely/php-sdk pull request #226
Opened 2021-07-19 11:47 UTC by ozayr-zaviar

## Summary
- Fixed an issue related to duplicate experiment_key.
- While trying to get variation from the variation_key_map, it was unable to find because the latest experimentKey was overriding the previous one.

## TestPlan
- Run with FSC

2021-07-26 23:33 UTC, zashraf1985 approved these changes
Looks Good! Just added a comment to fix a redundant variable assignment.

2021-07-26 23:33 UTC, zashraf1985 commented on src/Optimizely/Optimizely.php
> +            $experimentId = null;
this looks redundant?

2021-07-27 06:26 UTC, yasirfolio3 commented
LGTM!

2021-07-28 18:48 UTC, jaeopt requested changes
All changes look good. A couple of suggestions -
1. can we add new test cases for duplicate keys (duplicate experiment keys, and/or duplicate delivery-rule keys)
2. I found this line is still vulnerable to duplicate keys. Can you confirm it's ok? https://github.com/optimizely/php-sdk/blob/14e336c895037d5b3629b002faf2ea2b0e021054/src/Optimizely/DecisionService/DecisionService.php#L599

2021-08-02 22:32 UTC, msohailhussain commented
> All changes look good. A couple of suggestions -
> 
> 1. can we add new test cases for duplicate keys (duplicate experiment keys, and/or duplicate delivery-rule keys)
> 2. I found this line is still vulnerable to duplicate keys. Can you confirm it's ok? https://github.com/optimizely/php-sdk/blob/14e336c895037d5b3629b002faf2ea2b0e021054/src/Optimizely/DecisionService/DecisionService.php#L599

Thanks Jae. Will take care of it.

2021-08-04 16:44 UTC, jaeopt approved these changes
LGTM

2021-08-04 16:46 UTC, merged