feat(ForcedDecisions): add forced-decisions APIs to OptimizelyUserContext
optimizely/php-sdk pull request #233
Opened 2021-10-06 11:45 UTC by mnoman09

## Summary
Add a set of new APIs for forced-decisions to OptimizelyUserContext:
- setForcedDecision
- getForcedDecision
- removeForcedDecision
- removeAllForcedDecision

The following legacy APIs for feature management are deprecated in favor of `decide` APIs:
- isFeatureEnabled
- getFeatureVariable{Type}
- getAllFeatureVariables
- getEnabledFeatures

## Test plan
- unit tests for the new APIs
- FSC tests with new test cases

2021-10-06 13:40 UTC, ozayr-zaviar commented on src/Optimizely/DecisionService/DecisionService.php
> +            if ($bucketedVariation != null) {
```suggestion
            if ($bucketedVariation) {
```

2021-10-06 13:41 UTC, ozayr-zaviar commented on src/Optimizely/Optimizely.php
> +        if ($forcedDecisionResponse != null) {
```suggestion
        if ($forcedDecisionResponse) {
```

2021-10-06 13:46 UTC, ozayr-zaviar commented on src/Optimizely/Optimizely.php
> +        $userContext = $this->createUserContext($userId, $attributes?: []);
`$attributes?: []` will send nothing in argument if attributes exist.

2021-10-06 14:04 UTC, ozayr-zaviar commented on src/Optimizely/OptimizelyUserContext.php
> +            $message = sprintf('Variation "%s" is mapped to "%s" and user "%s" in the forced decision map.', $variationKey, $flagKey, $this->userId);
should print rule key as well if set in forced decision

2021-11-02 23:44 UTC, dustin-sier commented on src/Optimizely/Config/DatafileProjectConfig.php
> +                $flagVariations = array_merge($flagVariations, array_filter(array_values($rule->getVariations()), function ($variation) use ($flagVariations) {
My understanding of closures in PHP suggests this is copying the value of $flagVariations and not referencing it. Not sure if this could provide an edge case where the $flagVariations array is modified outside of this set of functions.

2021-11-03 00:36 UTC, dustin-sier commented on src/Optimizely/Optimizely.php
> +                "Optimizely SDK not configured properly yet."
Is there a static message for this that can be referenced?

2021-11-03 00:44 UTC, dustin-sier requested changes
Have a few questions, once that's done LGTM

2021-11-03 00:44 UTC, dustin-sier commented on src/Optimizely/OptimizelyUserContext.php
> +        if (!$this->forcedDecisions) {
Any reason to do this vs. isset?

2021-11-04 08:31 UTC, ozayr-zaviar approved these changes

2021-11-04 17:37 UTC, dustin-sier approved these changes
Looks good!

2021-11-04 18:47 UTC, merged