FIX: Forced variation not available in experiment
optimizely/php-sdk pull request #237
Opened 2021-12-13 16:17 UTC by mnoman09

## Summary
- Searching forced decision variation from flags first if its not available then we search it in experiment variation map. This is because of forced decision setting variation of flag delivery rule and setting rule key of experiment rule 

## Test plan
All unit test and FSC tests should pass

2021-12-13 23:14 UTC, msohailhussain commented on src/Optimizely/Event/Builder/EventBuilder.php
> +        $variation = $config->getFlagVariationByKey($flagKey, $variationKey);
is the variation returned correct?

2021-12-13 23:17 UTC, msohailhussain commented on src/Optimizely/Event/Builder/EventBuilder.php
> +        $variation = $config->getFlagVariationByKey($flagKey, $variationKey);
Please add a comment above this line that mapped flagKey can be directly used in variation so no experimentKey exist.

2021-12-13 23:56 UTC, msohailhussain commented on src/Optimizely/Event/Builder/EventBuilder.php
> +        $variation = $config->getFlagVariationByKey($flagKey, $variationKey);
Please add a check here, this is only valid for feature test not for ab. so flag_key must be non-empty.

2021-12-16 00:20 UTC, jaeopt requested changes
See comments

2021-12-16 00:20 UTC, jaeopt commented on src/Optimizely/Event/Builder/EventBuilder.php
> +        $variation = $config->getFlagVariationByKey($flagKey, $variationKey);
It looks like we need check empty both 'flagKey' (line 256) and 'experimentId' (line 260).
Also consider switching line 260 and 256 since 256 is common cases while 256 is for FD only and slow.

2021-12-20 17:11 UTC, jaeopt requested changes
The change looks good! Can we have a unit test covering these cases?

2021-12-21 12:55 UTC, mnoman09 commented
@jaeopt I have already added the test you can see this commit [link](https://github.com/optimizely/php-sdk/pull/237/commits/7adcf214ee3b9d4e5d0504a2a9060a89b53bfaa8).

2021-12-21 17:02 UTC, jaeopt commented
@mnoman09 ah ok, I was confused. all looks good!

2021-12-21 17:03 UTC, jaeopt approved these changes
LGTM

2021-12-22 06:07 UTC, msohailhussain approved these changes
lgtm

2021-12-22 06:08 UTC, merged