[FSSDK-8940] Correct return type hints
optimizely/php-sdk pull request #265
Opened 2023-03-27 19:55 UTC by rafinutshaw-optimizely

## Summary
- Check if testcases pass after fixing the hints as suggested in the PRs of the issue

## Test plan
- No changes here

## Issues
- https://jira.sso.episerver.net/browse/FSSDK-8940

2023-03-27 20:58 UTC, mikechu-optimizely requested changes
Please review about copyright notices.

2023-03-27 20:58 UTC, mikechu-optimizely commented on src/Optimizely/OptimizelyUserContext.php
@rafinutshaw-optimizely We'll need to increment the Copyright notice too for each file.

`Copyright 2021-2023, Optimizely`

2023-03-27 20:58 UTC, mikechu-optimizely commented on src/Optimizely/UserProfile/UserProfileServiceInterface.php
I think this one should be: `Copyright 2017, 2023, Optimizely Inc, and Contributors`

Is that cool?

2023-03-27 21:01 UTC, mikechu-optimizely commented
This PR once merged and released should resolve: #250, #254, & #259

2023-03-28 07:52 UTC, rafinutshaw-optimizely commented on src/Optimizely/UserProfile/UserProfileServiceInterface.php
yep, missed the copyright changes. thanks for pointing them out

2023-03-28 08:06 UTC, merged